name: dynamic_parallel_queue
description: A easy to use and dynamic parallel queue.
version: 1.0.0
homepage: https://github.com/gzlock/flutter_dynamic_parallel_queue

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: