name: dynamic_parallel_queue
description: A easy to use and dynamic parallel queue. Support priority setting.

version: 1.0.3+2
homepage: https://github.com/gzlock/flutter_dynamic_parallel_queue

environment:
  sdk: '>=2.16.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter: